apiVersion: v1
kind: ConfigMap
metadata:
  name: rentifyx-identity-api-config
data:
  AWS__Region: "sa-east-1"
  AWS__DynamoDB__TableName: "rentifyx-production-identity"
  OTEL_SERVICE_NAME: "RentifyxIdentity.Api"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=production"
